/*
 *
 *	Adventure Creator
 *	by Chris Burton, 2013-2019
 *	
 *	"Speech.cs"
 * 
 *	A container class for an active line of dialogue.
 * 
 */

using UnityEngine;
using System.Collections.Generic;

namespace AC
{

	/**
	 * A container class for an active line of dialogue.
	 */
	#if !(UNITY_4_6 || UNITY_4_7 || UNITY_5_0)
	[HelpURL("http://www.adventurecreator.org/scripting-guide/class_a_c_1_1_speech.html")]
	#endif
	public class Speech
	{

		/** The line's SpeechLog entry */
		public SpeechLog log;
		/** The display text */
		public string displayText { get; private set; }
		/** True if the line should play in the backround, and not interrupt Actions or gameplay. */
		public bool isBackground { get; private set; }
		/** True if the line is active */
		public bool isAlive;
		/** If True, the speech line has an AudioClip supplied */
		public bool hasAudio { get; private set; }
		/** If True, then the Action that ran this speech will end, but the speech line is still active */
		public bool continueFromSpeech = false;
		
		private int gapIndex = -1;
		private int continueIndex = -1;
		private List<SpeechGap> speechGaps = new List<SpeechGap>();
		private float endTime;
		private float continueTime;
		private float minSkipTime;
		private bool preventSkipping = false;

		/** The characters speaking the line, unless a narration */
		public AC.Char speaker { get; private set; }
		private bool isSkippable;
		private bool pauseGap;
		private bool holdForever = false;

		private float scrollAmount = 0f;
		private float pauseEndTime = 0f;
		private bool pauseIsIndefinite = false;
		private AudioSource audioSource = null;

		private bool isRTL = false;

		private RichTextTag[] richTextTags;

		private string closingTags = "";

		private float minDisplayTime;


		/**
		 * <summary>The default Constructor.</summary>
		 * <param name = "_speaker">The speaking character. If null, the line is considered a narration</param>
		 * <param name = "_message">The subtitle text to display</param>
		 * <param name = "lineID">The unique ID number of the line, as generated by the Speech Manager</param>
		 * <param name = "_language">The currently-selected language</param>
		 * <param name = "_isBackground">True if the line should play in the background, and not interrupt Actions or gameplay</param>
		 * <param name = "_noAnimation">True if the speaking character should not play a talking animation</param>
		 * <param name = "_preventSkipping">True if the speech cannot be skipped regardless of subtitle settings in the Speech Manager</param>
		 */
		public Speech (Char _speaker, string _message, int lineID, string _language, bool _isBackground, bool _noAnimation, bool _preventSkipping = false)
		{
			isRTL = KickStarter.runtimeLanguages.LanguageReadsRightToLeft (_language);

			closingTags = string.Empty;

			log.Clear ();
			isBackground = _isBackground;
			preventSkipping = _preventSkipping;
			richTextTags = GenerateRichTextTags (KickStarter.dialog.richTextTags);

			string realName = string.Empty;
			if (_speaker)
			{
				speaker = _speaker;
				speaker.isTalking = !_noAnimation;
				log.speakerName = realName = _speaker.name;
				
				if (_speaker.GetComponent <Player>())
				{
					if (KickStarter.settingsManager.playerSwitching == PlayerSwitching.Allow || !KickStarter.speechManager.usePlayerRealName)
					{
						log.speakerName = "Player";
					}
				}

				Hotspot speakerHotspot = _speaker.GetComponent <Hotspot>();
				if (speakerHotspot != null)
				{
					if (!string.IsNullOrEmpty (speakerHotspot.hotspotName))
					{
						log.speakerName = realName = speakerHotspot.hotspotName;
					}
				}

				if (KickStarter.speechManager.resetExpressionsEachLine)
				{
					_speaker.ClearExpression ();
				}

				if (!_noAnimation)
				{
					if (KickStarter.speechManager.lipSyncMode == LipSyncMode.Off)
					{
						speaker.isLipSyncing = false;
					}
					else if (KickStarter.speechManager.lipSyncMode == LipSyncMode.Salsa2D || KickStarter.speechManager.lipSyncMode == LipSyncMode.FromSpeechText || KickStarter.speechManager.lipSyncMode == LipSyncMode.ReadPamelaFile || KickStarter.speechManager.lipSyncMode == LipSyncMode.ReadSapiFile || KickStarter.speechManager.lipSyncMode == LipSyncMode.ReadPapagayoFile)
					{
						speaker.StartLipSync (KickStarter.dialog.GenerateLipSyncShapes (KickStarter.speechManager.lipSyncMode, lineID, speaker, _language, _message));
					}
					else if (KickStarter.speechManager.lipSyncMode == LipSyncMode.RogoLipSync)
					{
						RogoLipSyncIntegration.Play (_speaker, lineID, _language);
					}
				}
			}
			else
			{
				if (speaker)
				{
					speaker.isTalking = false;
				}
				speaker = null;			
				log.speakerName = realName = "Narrator";
			}
			
			if (CanScroll () && KickStarter.speechManager != null && KickStarter.speechManager.textScrollSpeed <= 0f)
			{
				ACDebug.LogWarning ("Text Scroll Speed must be greater than zero - please amend your Speech Manager");
			}

			if (Application.isPlaying)
			{
				_message = DetermineGaps (_message);
				_message = FindSpeakerTag (_message, realName);
			}

			if (speechGaps.Count > 0)
			{
				gapIndex = 0;
			}
			else
			{
				gapIndex = -1;
			}

			if (lineID > -1)
			{
				log.lineID = lineID;
			}

			// Play sound and time displayDuration to it
			if (lineID > -1 && !string.IsNullOrEmpty (log.speakerName) && KickStarter.speechManager.searchAudioFiles)
			{
				AudioClip clipObj = KickStarter.runtimeLanguages.GetSpeechAudioClip (lineID, _speaker);

				if (clipObj)
				{
					audioSource = null;

					if (_speaker != null)
					{
						if (!_noAnimation)
						{
							if (KickStarter.speechManager.lipSyncMode == LipSyncMode.FaceFX)
							{
								FaceFXIntegration.Play (speaker, log.speakerName + lineID, clipObj);
							}
						}

						if (_speaker.speechAudioSource)
						{
							audioSource = _speaker.speechAudioSource;
							_speaker.SetSpeechVolume (Options.optionsData.speechVolume);
						}
						else
						{
							ACDebug.LogWarning (_speaker.name + " has no audio source component!", _speaker);
						}
					}
					else
					{
						audioSource = KickStarter.dialog.GetNarratorAudioSource ();

						if (audioSource == null)
						{
							ACDebug.LogWarning ("Cannot play audio for speech line '" + _message + "' as there is no AudioSource - assign a new 'Default Sound' in the Scene Manager.");
						}
					}
					
					if (audioSource != null)
					{
						audioSource.clip = clipObj;
						audioSource.loop = false;
						audioSource.Play ();
						hasAudio = true;
					}
				}
			}

			float displayDuration = 0f;
			if (hasAudio)
			{
				displayDuration = KickStarter.speechManager.screenTimeFactor * 5f;
			}
			else if (!CanScroll () || KickStarter.speechManager.scrollingTextFactorsLength)
			{
				float totalWaitTime = GetLengthWithoutRichText (_message) - GetTotalWaitTokenDuration ();
				if (totalWaitTime < 0f)
				{
					totalWaitTime = 0.1f;
				}

				displayDuration = KickStarter.speechManager.screenTimeFactor * totalWaitTime;
			}
			else
			{
				displayDuration = KickStarter.speechManager.screenTimeFactor * 5f;
			}

			displayDuration = Mathf.Max (displayDuration, 0.1f);
			log.fullText = _message;
			KickStarter.eventManager.Call_OnStartSpeech (_speaker, log.fullText, lineID);

			if (!CanScroll ())
			{
				if (continueIndex > 0)
				{
					continueTime = (continueIndex / KickStarter.speechManager.textScrollSpeed);
				}
				
				if (speechGaps.Count > 0)
				{
					displayText = log.fullText.Substring (0, speechGaps[0].characterIndex);
				}
				else
				{
					displayText = log.fullText;
				}
			}
			else
			{
				displayText = string.Empty;
				KickStarter.eventManager.Call_OnStartSpeechScroll (_speaker, log.fullText, lineID);
			}

			isAlive = true;
			isSkippable = true;
			pauseGap = false;
			endTime = displayDuration;

			minSkipTime = KickStarter.speechManager.skipThresholdTime;
			minDisplayTime = Mathf.Max (0f, KickStarter.speechManager.minimumDisplayTime);

			if (endTime <= 0f)
			{
				EndMessage ();
			}
		}


		/** Updates the speech volume to the level set in Options.  This should be called whenever the Speech volume level is changed. */
		public void UpdateVolume ()
		{
			if (speaker)
			{
				speaker.SetSpeechVolume (Options.optionsData.speechVolume);
			}
		}


		/**
		 * <summary>A special-case Constructor purely used to display text without tags when exporting script-sheets.</summary>
		 * <param name = "_message">The subtitle text to display</param>
		 */
		public Speech (string _message)
		{
			if (Application.isPlaying)
			{
				displayText = DetermineGaps (_message);
				richTextTags = GenerateRichTextTags (KickStarter.dialog.richTextTags);
			}
			else
			{
				displayText = _message;
			}
		}


		private RichTextTag[] GenerateRichTextTags (string[] tagNames)
		{
			List<RichTextTag> tagsList = new List<RichTextTag>();
			foreach (string tagName in tagNames)
			{
				if (!string.IsNullOrEmpty (tagName))
				{
					RichTextTag newTag = new RichTextTag (tagName);
					if (!tagsList.Contains (newTag))
					{
						tagsList.Add (newTag);
					}
				}
			}
			return tagsList.ToArray ();
		}


		/**
		 * Updates the state of the line.
		 * This is called every LateUpdate call by StateHandler.
		 */
		public void UpdateDisplay ()
		{
			if (minSkipTime > 0f)
			{
				minSkipTime -= Time.deltaTime;
			}

			if (minDisplayTime > 0f)
			{
				minDisplayTime -= Time.deltaTime;
			}

			if (pauseEndTime > 0f)
			{
				pauseEndTime -= Time.deltaTime;
			}

			if (pauseGap)
			{
				if (!pauseIsIndefinite && pauseEndTime <= 0f)
				{
					EndPause ();
				}
				else
				{
					return;
				}
			}
			else
			{
				if (hasAudio && !audioSource.isPlaying)
				{
					if (endTime > 0f)
					{
						endTime -= Time.deltaTime;
					}
				}
				else if (!hasAudio)
				{
					if (!CanScroll () || scrollAmount >= 1f)
					{
						if (endTime > 0f)
						{
							endTime -= Time.deltaTime;
						}
					}
				}
			}

			if (CanScroll ())
			{
				if (scrollAmount < 1f)
				{
					if (!pauseGap)
					{
						scrollAmount += KickStarter.speechManager.textScrollSpeed * Time.deltaTime / 2f / log.fullText.Length;

						if (scrollAmount >= 1f)
						{
							StopScrolling ();
						}

						int currentCharIndex = 0;
						if (isRTL)
						{
							currentCharIndex = (int) ((1f - scrollAmount) * log.fullText.Length);
						}
						else
						{
							currentCharIndex = (int) (scrollAmount * log.fullText.Length);
						}

						string newText = GetTextPortion (log.fullText, currentCharIndex);

						if (displayText != newText && !hasAudio)
						{
							KickStarter.dialog.PlayScrollAudio (speaker);
						}
						
						displayText = newText;
						if (gapIndex >= 0 && speechGaps.Count > gapIndex)
						{
							if (HasPassedIndex (currentCharIndex, speechGaps[gapIndex].characterIndex))
							{
								SetPauseGap ();
								return;
							}
						}

						if (continueIndex >= 0)
						{
							if (HasPassedIndex (currentCharIndex, continueIndex))
							{
								continueIndex = -1;
								continueFromSpeech = true;
							}
						}
					}
					return;
				}
				displayText = log.fullText;
			}
			else
			{
				if (gapIndex >= 0 && speechGaps.Count >= gapIndex)
				{
					if (gapIndex == speechGaps.Count)
					{
						displayText = log.fullText;
					}
					else
					{
						float waitTime = (float) speechGaps[gapIndex].waitTime;

						if (isRTL)
						{
							displayText = log.fullText.Substring (speechGaps[gapIndex].characterIndex);
						}
						else
						{
							displayText = log.fullText.Substring (0, speechGaps[gapIndex].characterIndex);
						}

						if (waitTime >= 0)
						{
							pauseEndTime = waitTime;
							pauseGap = true;

							speechGaps[gapIndex].CallEvent (speaker, log.lineID);
						}
						else if (speechGaps[gapIndex].expressionID >= 0)
						{
							speaker.SetExpression (speechGaps [gapIndex].expressionID);
							gapIndex ++;
						}
						else
						{
							pauseIsIndefinite = true;
							pauseGap = true;
						}
					}
				}
				else
				{
					displayText = log.fullText;
				}
				
				if (continueIndex >= 0)
				{
					if (continueTime > 0f)
					{
						continueFromSpeech = true;
					}
				}
			}

			if (endTime <= 0f && minDisplayTime <= 0f)
			{
				if (KickStarter.speechManager.displayForever)
				{
					if (isBackground)
					{
						EndMessage ();
					}
					else
					{
						if (!hasAudio || !audioSource.isPlaying)
						{
							if (!KickStarter.speechManager.playAnimationForever && speaker != null && speaker.isTalking)
							{
								speaker.StopSpeaking ();
							}
						}
					}
				}
				else
				{
					if (speaker == null && KickStarter.speechManager.displayNarrationForever)
					{}
					else
					{
						EndMessage ();
					}
				}
			}
		}


		private bool HasPassedIndex (int currentCharIndex, int indexToCheck)
		{
			if (isRTL)
			{
				return (currentCharIndex <= indexToCheck);
			}
			return (currentCharIndex >= indexToCheck);
		}


		/**
		 * Ends the current pause.
		 */
		public void EndPause ()
		{
			pauseEndTime = 0f;
			pauseGap = false;
			pauseIsIndefinite = false;
			gapIndex ++;
			//scrollAmount = 0f;

			if (CanScroll ())
			{
				KickStarter.eventManager.Call_OnStartSpeechScroll (speaker, log.fullText, log.lineID);
			}
		}


		/**
		 * <summary>Checks if the speech line matches certain conditions.</summary>
		 * <param name = "speechMenuLimit">What kind of speech has to play for this Menu to enable (All, BlockingOnly, BackgroundOnly)</param>
		 * <param name = "speechMenuType">What kind of speaker has to be speaking for this Menu to enable (All, CharactersOnly, NarrationOnly, SpecificCharactersOnly)</param>
		 * <param name = "limitToCharacters">A list of character names that this Menu will show for, if speechMenuType = SpeechMenuType.SpecificCharactersOnly</param>
		 * <param name = "speechProximityLimit">Whether or not the distance the Player/MainCamera is from the speaking character affects display</param>
		 * <param name = "speechProximityDistance">The maximum distance if speechProximityLimit != SpeechProximityLimit.NoLimit"</param>
		 * <returns>True if the speech line matches the conditions</returns>
		 */
		public bool HasConditions (SpeechMenuLimit speechMenuLimit, SpeechMenuType speechMenuType, string limitToCharacters, SpeechProximityLimit speechProximityLimit = SpeechProximityLimit.NoLimit, float speechProximityDistance = 0f)
		{
			if (speaker != null && speechProximityDistance > 0f)
			{
				if (speechProximityLimit == SpeechProximityLimit.LimitByDistanceToCamera)
				{
					float distance = Vector3.Distance (speaker.transform.position, Camera.main.transform.position);
					if (distance > speechProximityDistance)
					{
						return false;
					}
				}
				else if (speechProximityLimit == SpeechProximityLimit.LimitByDistanceToPlayer && KickStarter.player != null)
				{
					float distance = Vector3.Distance (speaker.transform.position, KickStarter.player.transform.position);
					if (distance > speechProximityDistance)
					{
						return false;
					}
				}
			}

			if (speechMenuLimit == SpeechMenuLimit.All ||
			    (speechMenuLimit == SpeechMenuLimit.BlockingOnly && !isBackground) ||
			    (speechMenuLimit == SpeechMenuLimit.BackgroundOnly && isBackground))
			{
				if (speechMenuType == SpeechMenuType.All ||
				    (speechMenuType == SpeechMenuType.CharactersOnly && speaker != null) ||
				    (speechMenuType == SpeechMenuType.NarrationOnly && speaker == null))
			    {
			    	return true;
			    }
				else if (speechMenuType == SpeechMenuType.SpecificCharactersOnly && speaker != null)
				{
					if (limitToCharacters.Contains (";" + GetSpeaker () + ";"))
					{
						return true;
					}
					else if (limitToCharacters.Contains (";Player;") && speaker != null && speaker.IsPlayer)
					{
						return true;
					}
				}
				else if (speechMenuType == SpeechMenuType.AllExceptSpecificCharacters && GetSpeakingCharacter () != null)
				{
					if (limitToCharacters.Contains (";" + GetSpeaker () + ";"))
					{
						return false;
					}
					else if (limitToCharacters.Contains (";Player;") && speaker != null && speaker.IsPlayer)
					{
						return false;
					}
					return true;
				}
			}
			    
			return false;
		}


		private void EndMessage (bool forceOff = false)
		{
			if (holdForever)
			{
				continueFromSpeech = true;
				return;
			}
			endTime = 0f;
			isSkippable = false;

			if (speaker)
			{
				speaker.StopSpeaking ();
			}

			EndSpeechAudio ();

			if (!forceOff && gapIndex >= 0 && gapIndex < speechGaps.Count)
			{
				gapIndex ++;
			}
			else
			{
				isAlive = false;
				KickStarter.stateHandler.UpdateAllMaxVolumes ();
			}
		}


		private bool SkipSpeechInput ()
		{
			if (minSkipTime > 0f || preventSkipping)
			{
				return false;
			}

			if (KickStarter.speechManager.canSkipWithMouseClicks && (KickStarter.playerInput.GetMouseState () == MouseState.SingleClick ||
			    													 KickStarter.playerInput.GetMouseState () == MouseState.RightClick))
			{
				return true;
			}

			if (KickStarter.playerInput.InputGetButtonDown ("SkipSpeech"))
			{
				return true;
			}

			return false;
		}


		/**
		 * <summary>Updates the state of the Speech based on the user's input.
		 * This is called every Update call by StateHandler.</summary>
		 */
		public void UpdateInput ()
		{
			if (isSkippable)
			{
				if (pauseGap && !IsBackgroundSpeech ())
				{
					if (SkipSpeechInput ())
					{
						if (speechGaps[gapIndex].waitTime < 0f)
						{
							KickStarter.playerInput.ResetMouseClick ();
							EndPause ();
						}
						else if (KickStarter.speechManager.allowSpeechSkipping)
						{
							KickStarter.playerInput.ResetMouseClick ();
							EndPause ();
						}
					}
				}
				
				else if ((KickStarter.speechManager.displayForever && !IsBackgroundSpeech ()) ||
						 (KickStarter.speechManager.displayNarrationForever && !IsBackgroundSpeech () && speaker == null))
				{
					if (SkipSpeechInput ())
					{
						if (holdForever && log.fullText == displayText)
						{
							// Ignore clicks
							return;
						}

						KickStarter.playerInput.ResetMouseClick ();
						
						if (KickStarter.stateHandler.gameState == GameState.Cutscene)
						{
							if (KickStarter.speechManager.endScrollBeforeSkip && CanScroll () && displayText != log.fullText)
							{
								// Stop scrolling
								StopScrolling ();

								if (speechGaps != null && speechGaps.Count > gapIndex)
								{
									// Call events
									for (int i=gapIndex; i<speechGaps.Count; i++)
									{
										if (gapIndex >= 0)
										{
											speechGaps[i].CallEvent (speaker, log.lineID);
										}
									}

									// Find last non-encountered expression
									for (int i=speechGaps.Count-1; i>=gapIndex; i--)
									{
										if (i >= 0 && speechGaps[i].expressionID >= 0)
										{
											speaker.SetExpression (speechGaps[i].expressionID);
											break; // was return
										}
									}
								}

								//
								if (continueIndex >= 0)
								{
									continueIndex = -1;
									continueFromSpeech = true;
								}
								//
							}
							else
							{
								// Stop message
								EndMessage (true);
							}
						}
						else
						{
							ACDebug.LogWarning ("Cannot skip the line " + log.fullText + " because it is not background speech but the gameState is not a Cutscene! Either mark it as background speech, or initiate a scripted cutscene with AC.KickStarter.stateHandler.StartCutscene ();");
						}
					}
				}
				
				else if (SkipSpeechInput ())
				{
					if ((KickStarter.speechManager.allowSpeechSkipping && !IsBackgroundSpeech ()) ||
						(KickStarter.speechManager.allowSpeechSkipping && KickStarter.speechManager.allowGameplaySpeechSkipping && IsBackgroundSpeech ()) ||
						(KickStarter.speechManager.displayForever && KickStarter.speechManager.allowGameplaySpeechSkipping && IsBackgroundSpeech ()) ||
						(KickStarter.speechManager.displayNarrationForever && speaker == null && KickStarter.speechManager.allowGameplaySpeechSkipping && IsBackgroundSpeech ()))
					{
						KickStarter.playerInput.ResetMouseClick ();
						
						if (KickStarter.stateHandler.gameState == GameState.Cutscene || (KickStarter.speechManager.allowGameplaySpeechSkipping && KickStarter.stateHandler.IsInGameplay ()))
						{
							if (KickStarter.speechManager.endScrollBeforeSkip && CanScroll () && displayText != log.fullText)
							{
								// Stop scrolling
								if (speechGaps.Count > 0 && speechGaps.Count > gapIndex)
								{
									while (gapIndex < speechGaps.Count && speechGaps[gapIndex].waitTime >= 0)
									{
										speechGaps[gapIndex].CallEvent (speaker, log.lineID);

										// Find next wait
										gapIndex ++;
									}
									
									if (gapIndex == speechGaps.Count)
									{
										ExtendTime ();
										StopScrolling ();
									}
									else
									{
										if (isRTL)
										{
											displayText = log.fullText.Substring (speechGaps[gapIndex].characterIndex);
										}
										else
										{
											displayText = log.fullText.Substring (0, speechGaps[gapIndex].characterIndex);
										}
										SetPauseGap ();
									}
								}
								else
								{
									ExtendTime ();
									StopScrolling ();
								}
							}
							else
							{
								EndMessage (true);
							}
						}
					}
				}
			}
		}


		private void ExtendTime ()
		{
			if (CanScroll () && !KickStarter.speechManager.scrollingTextFactorsLength && !hasAudio)
			{
				// Extend length of speech display, since its been skipped prematurely
				float timeExtension = (1f - scrollAmount) * KickStarter.speechManager.screenTimeFactor * GetLengthWithoutRichText (log.fullText);
				endTime = Mathf.Max (endTime, timeExtension);
			}
		}


		private void StopScrolling ()
		{
			scrollAmount = 1f;
			displayText = log.fullText;
			
			if (holdForever)
			{
				continueFromSpeech = true;
			}

			// Call events
			KickStarter.eventManager.Call_OnEndSpeechScroll (speaker, log.fullText, log.lineID);
			KickStarter.eventManager.Call_OnCompleteSpeechScroll (speaker, log.fullText, log.lineID);
		}


		private void SetPauseGap ()
		{
			scrollAmount = (float) speechGaps [gapIndex].characterIndex / (float) log.fullText.Length;
			if (isRTL)
			{
				scrollAmount = 1f - scrollAmount;
			}

			float waitTime = speechGaps [gapIndex].waitTime;
			pauseGap = true;
			pauseIsIndefinite = false;

			if (speechGaps [gapIndex].pauseIsIndefinite)
			{
				pauseEndTime = 0f;
				pauseIsIndefinite = true;
			}
			else if (waitTime >= 0f)
			{
				pauseEndTime = waitTime;
				speechGaps[gapIndex].CallEvent (speaker, log.lineID);
			}
			else if (speechGaps [gapIndex].expressionID >= 0)
			{
				pauseEndTime = 0f;
				speaker.SetExpression (speechGaps [gapIndex].expressionID);
			}
			else
			{
				pauseEndTime = 0f;
			}

			if (pauseEndTime > 0f || pauseIsIndefinite)
			{
				// Call event
				KickStarter.eventManager.Call_OnEndSpeechScroll (speaker, log.fullText, log.lineID);
			}
		}


		private string DetermineGaps (string _text)
		{
			speechGaps.Clear ();
			continueIndex = -1;

			if (!string.IsNullOrEmpty (_text))
			{
				string[] eventKeys = KickStarter.dialog.SpeechEventTokenKeys;

				for (int i=0; i<_text.Length; i++)
				{
					string textPortion1 = _text.Substring (0, i);
					string textPortion2 = _text.Substring (i);

					if (textPortion2.StartsWith ("[continue]"))
					{
						continueIndex = i;

						_text = textPortion1 + textPortion2.Substring ("[continue]".Length);
						CorrectPreviousGaps (continueIndex, 10);

						i = -1;
						continue;
					}
					else if (textPortion2.StartsWith ("[hold]"))
					{
						if (continueIndex == -1)
						{
							continueIndex = i;
						}

						_text = textPortion1 + textPortion2.Substring ("[hold]".Length);
						holdForever = true;
						CorrectPreviousGaps (continueIndex, 6);

						i = -1;
						continue;
					}
					else if (textPortion2.StartsWith ("[expression:") && speaker != null)
					{
						// Expression change
						int endIndex = textPortion2.IndexOf ("]");
						string expressionText = textPortion2.Substring (12, endIndex - 12);
						int expressionID = speaker.GetExpressionID (expressionText);

						speechGaps.Add (new SpeechGap (i, expressionID));
						_text = textPortion1 + textPortion2.Substring (endIndex + 1);

						i = -1;
						continue;
					}
					else if (textPortion2.StartsWith ("[wait]"))
					{
						// Indefinite wait
						speechGaps.Add (new SpeechGap (i, true));
						_text = textPortion1 + textPortion2.Substring ("[wait]".Length);

						i = -1;
						continue;
					}
					else if (textPortion2.StartsWith ("[wait:"))
					{
						// Timed wait
						int endIndex = textPortion2.IndexOf ("]");
						string waitTimeText = textPortion2.Substring (6, endIndex - 6);

						speechGaps.Add (new SpeechGap (i, FloatParse (waitTimeText)));
						_text = textPortion1 + textPortion2.Substring (endIndex + 1);

						i = -1;
						continue;
					}
					else if (eventKeys != null)
					{
						foreach (string eventKey in eventKeys)
						{
							if (string.IsNullOrEmpty (eventKey)) continue;

							string keyStart = "[" + eventKey + ":";
							if (textPortion2.StartsWith (keyStart))
							{
								int endIndex = textPortion2.IndexOf ("]");
								string eventValue = textPortion2.Substring (keyStart.Length, endIndex - keyStart.Length);

								speechGaps.Add (new SpeechGap (i, eventKey, eventValue));
								_text = textPortion1 + textPortion2.Substring (endIndex + 1);

								i = -1;
								continue;
							}
						}
					}
				}
			}

			// Sort speechGaps
			if (speechGaps.Count > 1)
			{
				if (isRTL)
				{
					speechGaps.Sort (delegate (SpeechGap b, SpeechGap a) {return a.characterIndex.CompareTo (b.characterIndex);});
				}
				else
				{
					speechGaps.Sort (delegate (SpeechGap a, SpeechGap b) {return a.characterIndex.CompareTo (b.characterIndex);});
				}
			}
			
			return _text;
		}


		private string FindSpeakerTag (string _message, string _speakerName)
		{
			if (!string.IsNullOrEmpty (_message))
			{
				if (_message.Contains ("[speaker]"))
				{
					_message = _message.Replace ("[speaker]", _speakerName);
				}
			}
			return _message;
		}


		private void CorrectPreviousGaps (int minCharIndex, int offset)
		{
			if (speechGaps.Count > 0)
			{
				for (int i=0; i<speechGaps.Count; i++)
				{
					if (speechGaps[i].characterIndex > minCharIndex)
					{
						SpeechGap speechGap = speechGaps[i];
						speechGap.characterIndex -= offset;
						speechGaps[i] = speechGap;
					}
				}
			}
		}


		private float FloatParse (string text)
		{
			float _value = 0f;
			if (!string.IsNullOrEmpty (text))
			{
				float.TryParse (text, out _value);
			}
			return _value;
		}


		private bool IsBackgroundSpeech ()
		{
			return isBackground;
		}


		/**
		 * <summary>Ends speech audio, if it is playing in the background.</summary>
		 * <param name = "newSpeaker">If the line's speaker matches this, the audio will not end</param>
		 */
		public void EndBackgroundSpeechAudio (AC.Char newSpeaker)
		{
			if (isBackground && hasAudio && speaker != null && speaker != newSpeaker)
			{
				if (speaker.speechAudioSource)
				{
					speaker.speechAudioSource.Stop ();
				}
			}
		}


		/**
		 * <summary>Ends speech audio, regardless of conditions.</summary>
		 */
		public void EndSpeechAudio ()
		{
			if (audioSource != null)
			{
				audioSource.Stop ();
			}
		}


		/**
		 * <summary>Gets the display name of the speaking character.</summary>
		 * <param name = "languageNumber">The index number of the language number to get the text in</param>
		 * <returns>The display name of the speaking character</returns>
		 */
		public string GetSpeaker (int languageNumber = 0)
		{
			if (speaker)
			{
				return speaker.GetName (languageNumber);
			}
			
			return string.Empty;
		}


		/**
		 * <summary>Gets the colour of the subtitle text.</summary>
		 * <returns>The colour of the subtitle text</returns>
		 */
		public Color GetColour ()
		{
			if (speaker)
			{
				return speaker.speechColor;
			}
			return Color.white;
		}
		

		/**
		 * <summary>Gets the speaking character.</summary>
		 * <returns>The speaking character</returns>
		 */
		public AC.Char GetSpeakingCharacter ()
		{
			return speaker;
		}


		/**
		 * <summary>Checks if the speech line is temporarily paused, due to a [wait] or [wait:X] token.</summary>
		 * <returns>True if the speech line is temporarily paused.</returns>
		 */
		public bool IsPaused ()
		{
			return pauseGap;
		}


		/**
		 * <summary>Gets a Sprite based on the portrait graphic of the speaking character.
		 * If lipsincing is enabled, the sprite will be based on the current phoneme.</summary>
		 * <returns>The speaking character's portrait sprite</returns>
		 */
		public UnityEngine.Sprite GetPortraitSprite ()
		{
			if (speaker != null)
			{
				CursorIconBase portraitIcon = speaker.GetPortrait ();
				if (portraitIcon != null && portraitIcon.texture != null)
				{
					if (IsAnimating ())
					{
						if (speaker.isLipSyncing)
						{
							return portraitIcon.GetAnimatedSprite (speaker.GetLipSyncFrame ());
						}
						else
						{
							return portraitIcon.GetAnimatedSprite (true);
						}
					}
					else
					{
						return portraitIcon.GetSprite ();
					}
				}
			}
			return null;
		}
		

		/**
		 * <summary>Gets the portrait graphic of the speaking character.</summary>
		 * <returns>The speaking character's portrait graphic</returns>
		 */
		public Texture GetPortrait ()
		{
			if (speaker && speaker.GetPortrait ().texture)
			{
				return speaker.GetPortrait ().texture;
			}
			return null;
		}
		

		/**
		 * <summary>Checks if the speaking character's portrait graphic can be animated.</summary>
		 * <returns>True if the character's portrait graphic can be animated</returns>
		 */
		public bool IsAnimating ()
		{
			if (speaker && speaker.GetPortrait ().isAnimated)
			{
				return true;
			}
			return false;
		}


		/**
		 * <summary>Gets a Rect of the character's portrait graphic.
		 * If the graphic is animating, only the relevant portion will be returned.</summary>
		 * <returns>A Rect of the character's portrait graphic</returns>
		 */
		public Rect GetAnimatedRect ()
		{
			if (speaker != null && speaker.GetPortrait () != null)
			{
				if (speaker.isLipSyncing)
				{
					return speaker.GetPortrait ().GetAnimatedRect (speaker.GetLipSyncFrame ());
				}
				else if (speaker.isTalking)
				{
					return speaker.GetPortrait ().GetAnimatedRect ();
				}
				else
				{
					return speaker.GetPortrait ().GetAnimatedRect (0);
				}
			}
			return new Rect (0,0,0,0);
		}


		private bool CanScroll ()
		{
			if (speaker == null)
			{
				return KickStarter.speechManager.scrollNarration;
			}
			return KickStarter.speechManager.scrollSubtitles;
		}


		/** The full display text of the line */
		public string FullText
		{
			get
			{
				return log.fullText;
			}
		}


		/** The display name of the speaking character */
		public string SpeakerName
		{
			get
			{
				return log.speakerName;
			}
		}


		/** The ID number of the line, as set by the Speech Manager */
		public int LineID
		{
			get
			{
				return log.lineID;
			}
		}


		/**
		 * <summary>Checks if a Menu is able to show this speech line.</summary>
		 * <param name = "menu">The Menu to check against</param>
		 * <returns>True if the Menu is able to show this speech line</returns>
		 */
		public bool MenuCanShow (Menu menu)
		{
			if (menu != null)
			{
				return HasConditions (menu.speechMenuLimit, menu.speechMenuType, menu.limitToCharacters, menu.speechProximityLimit, menu.speechProximityDistance);
			}
			return false;
		}


		private string GetTextPortion (string fullText, int originalIndex)
		{
			if (isRTL)
			{
				if (fullText.Length < originalIndex)
				{
					return string.Empty;
				}
				else if (originalIndex == 0)
				{
					return fullText;
				}
			}
			else
			{
				if (fullText.Length < originalIndex)
				{
					return string.Empty;
				}
				else if (fullText.Length == originalIndex)
				{
					return fullText;
				}
			}

			int newIndex = originalIndex;
			bool hasTag = false;
			if (isRTL)
			{
				hasTag = (fullText[newIndex].ToString () == ">");
			}
			else
			{
				hasTag = (fullText[newIndex].ToString () == "<");
			}

			if (!hasTag && !UsingRichText ())
			{
				// No rich tags right now, so don't do anything complicated
				if (isRTL)
				{
					return fullText.Substring (newIndex);
				}
				return fullText.Substring (0, newIndex);
			}

			if (hasTag)
			{
				if (isRTL)
				{
					string stringFromIndex = fullText.Substring (0, newIndex+1);

					// Check for closing

					for (int i=0; i<richTextTags.Length; i++)
					{
						if (stringFromIndex.EndsWith (richTextTags[i].closeTag))
						{
							if (richTextTags[i].usesParameters)
							{
								int lastIndex = stringFromIndex.LastIndexOf (richTextTags[i].openTag);
								if (lastIndex >= 0)
								{
									int lastIndexEnd = stringFromIndex.IndexOf (">", lastIndex);
									if (lastIndexEnd >= 0 && lastIndexEnd > lastIndex)
									{
										string detectedParameter = stringFromIndex.Substring (lastIndex + richTextTags[i].openTag.Length, lastIndexEnd - lastIndex - richTextTags[i].openTag.Length);
										if (!string.IsNullOrEmpty (detectedParameter))
										{
											richTextTags[i].activeParameter = richTextTags[i].openTag + detectedParameter + ">";
											closingTags += richTextTags[i].activeParameter;

											richTextTags[i].tagIndex -= stringFromIndex.IndexOf (richTextTags[i].openTag);
											newIndex -= richTextTags[i].closeTag.Length;
										}
									}
								}
							}
							else
							{
								richTextTags[i].tagIndex = -stringFromIndex.IndexOf (richTextTags[i].openTag) + newIndex;
								newIndex -= richTextTags[i].closeTag.Length;
								closingTags = closingTags + richTextTags[i].openTag;
							}
							break;
						}
					}

					// Check for opening

					for (int i=0; i<richTextTags.Length; i++)
					{
						if (richTextTags[i].usesParameters)
						{
							if (!string.IsNullOrEmpty (richTextTags[i].activeParameter) && stringFromIndex.EndsWith (richTextTags[i].activeParameter))
							{
								richTextTags[i].tagIndex = -1;
								newIndex -= richTextTags[i].activeParameter.Length;
								closingTags = closingTags.Replace (richTextTags[i].activeParameter, string.Empty);
								richTextTags[i].activeParameter = string.Empty;
								break;
							}
						}
						else
						{
							if (stringFromIndex.EndsWith (richTextTags[i].openTag))
							{
								richTextTags[i].tagIndex = -1;
								newIndex -= richTextTags[i].openTag.Length;
								closingTags = closingTags.Replace (richTextTags[i].openTag, string.Empty);
								break;
							}
						}
					}
				
					// Modified currentCharIndex, so convert back to scrollAmount
					// NOTE! Only increase, don't set explicitly - otherwise errors with wait tokens
					scrollAmount += (float) -(newIndex - originalIndex) / (float) fullText.Length;
				}
				else
				{
					string stringFromIndex = fullText.Substring (newIndex);

					// Check for opening
					for (int i=0; i<richTextTags.Length; i++)
					{
						if (stringFromIndex.StartsWith (richTextTags[i].openTag))
						{
							if (richTextTags[i].usesParameters)
							{
								richTextTags[i].tagIndex += stringFromIndex.IndexOf (richTextTags[i].closeTag);
								int closeBracketIndex = stringFromIndex.IndexOf (">") + 1;
								newIndex += closeBracketIndex;
								closingTags = richTextTags[i].closeTag + closingTags;
							}
							else
							{
								richTextTags[i].tagIndex = stringFromIndex.IndexOf (richTextTags[i].closeTag) + newIndex;
								newIndex += richTextTags[i].openTag.Length;
								closingTags = richTextTags[i].closeTag + closingTags;
							}
							break;
						}
					}
					
					// Check for closing
					for (int i=0; i<richTextTags.Length; i++)
					{
						if (stringFromIndex.StartsWith (richTextTags[i].closeTag))
						{
							if (richTextTags[i].usesParameters)
							{
								richTextTags[i].tagIndex = -1;
								newIndex += richTextTags[i].closeTag.Length;
								closingTags = closingTags.Replace (richTextTags[i].closeTag, string.Empty);
							}
							else
							{
								richTextTags[i].tagIndex = -1;
								newIndex += richTextTags[i].closeTag.Length;
								closingTags = closingTags.Replace (richTextTags[i].closeTag, string.Empty);
							}
							break;
						}
					}

					// Modified currentCharIndex, so convert back to scrollAmount
					// NOTE! Only increase, don't set explicitly - otherwise errors with wait tokens
					scrollAmount += (float) (newIndex - originalIndex) / (float) fullText.Length;
				}
			}

			if (isRTL)
			{
				return closingTags + fullText.Substring (newIndex);
			}
			return fullText.Substring (0, newIndex) + closingTags;
		}


		private float GetLengthWithoutRichText (string _message)
		{
			for (int i=0; i<richTextTags.Length; i++)
			{
				_message = richTextTags[i].RemoveTagFromString (_message);
			}

			_message = _message.Replace ("[var:", string.Empty);
			_message = _message.Replace ("[localvar:", string.Empty);
			_message = _message.Replace ("[wait:", string.Empty);
			_message = _message.Replace ("[continue:", string.Empty);
			_message = _message.Replace ("[expression:", string.Empty);
			_message = _message.Replace ("[paramlabel:", string.Empty);
			_message = _message.Replace ("[param:", string.Empty);

			return (float) _message.Length;
		}


		private float GetTotalWaitTokenDuration ()
		{
			if (speechGaps != null && speechGaps.Count > 0f)
			{
				float totalDuration = 0f;
				foreach (SpeechGap speechGap in speechGaps)
				{
					if (speechGap.waitTime > 0f)
					{
						totalDuration += speechGap.waitTime;
					}
				}

				return totalDuration;
			}

			return 0f;
		}


		private bool UsingRichText ()
		{
			for (int i=0; i<richTextTags.Length; i++)
			{
				if (richTextTags[i].tagIndex != -1)
				{
					return true;
				}
			}
			return false;
		}


		private struct RichTextTag
		{

			public int tagIndex;
			public string openTag { get; private set; }
			public string closeTag { get; private set; }
			public bool usesParameters { get; private set; }
			public string activeParameter;


			public RichTextTag (string tag)
			{
				tagIndex = -1;
				activeParameter = string.Empty;

				if (tag.Contains ("="))
				{
					usesParameters = true;
					openTag = "<" + tag;
					closeTag = "</" + tag.Substring (0, tag.Length-1) + ">";
				}
				else
				{
					usesParameters = false;
					openTag = "<" + tag + ">";
					closeTag = "</" + tag + ">";
				}
			}


			public string RemoveTagFromString (string text)
			{
				text = text.Replace (openTag, string.Empty);
				text = text.Replace (closeTag, string.Empty);
				return text;
			}

		}

	}


	/**
	 * A data struct for an entry in the game's speech log.
	 */
	public struct SpeechLog
	{

		/** The full display text of the line */
		public string fullText;
		/** The display name of the speaking character */
		public string speakerName;
		/** The ID number of the line, as set by the Speech Manager */
		public int lineID;


		/**
		 * Clears the struct.
		 */
		public void Clear ()
		{
			fullText = string.Empty;
			speakerName = string.Empty;
			lineID = -1;
		}

	}


	/**
	 * A data container for an label a 'Dialogue: Play speech' Action can be tagged as
	 */
	[System.Serializable]
	public class SpeechTag
	{
		
		/** A unique identified */
		public int ID;
		/** The tag's text */
		public string label;
		
		
		/**
		 * <summary>The default Constructor.</summary>
		 * <param name = "idArray">An array of already-used ID numbers, so that a unique one can be generated</param>
		 */
		public SpeechTag (int[] idArray)
		{
			ID = 0;
			label = string.Empty;
			
			// Update id based on array
			if (idArray != null && idArray.Length > 0)
			{
				foreach (int _id in idArray)
				{
					if (ID == _id)
						ID ++;
				}
			}
		}


		/**
		 * <summary>A Constructor for the first SpeechTag.</summary>
		 * <param name = "_label">The SpeechTag's label</param>
		 */
		public SpeechTag (string _label)
		{
			ID = 0;
			label = _label;
		}
		
	}

}